services:
  medusajs:
    image: reg.ksstorm.dev/node-postgres:0.0.4
    container_name: medusajs-server
    hostname: server
    restart: always
    ports:
     - 9000:9000
    environment:
     - DATABASE_URL=postgres://medusajs:medusajs@localhost:5432/medusadb
     - REDIS_URL=redis://localhost:6379

